/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
  aws_project_region: 'eu-central-1',
  aws_cognito_identity_pool_id:
    'eu-central-1:5d9b8455-5615-446a-91d3-65ec703dbeab',
  aws_cognito_region: 'eu-central-1',
  aws_user_pools_id: 'eu-central-1_v4kYZUsIS',
  aws_user_pools_web_client_id: '6rcl32iktc4lr0sg288ljmm6fh',
  oauth: {},
};

export default awsmobile;
