/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "eu-central-1",
    "aws_cognito_identity_pool_id": "eu-central-1:5d9b8455-5615-446a-91d3-65ec703dbeab",
    "aws_cognito_region": "eu-central-1",
    "aws_user_pools_id": "eu-central-1_v4kYZUsIS",
    "aws_user_pools_web_client_id": "6rcl32iktc4lr0sg288ljmm6fh",
    "oauth": {},
    "aws_appsync_graphqlEndpoint": "https://v4z7xrfh2zd4lfrvlmxv3xt5bu.appsync-api.eu-central-1.amazonaws.com/graphql",
    "aws_appsync_region": "eu-central-1",
    "aws_appsync_authenticationType": "API_KEY",
    "aws_appsync_apiKey": "da2-47bc623v4veabhldbcdwkotmvu"
};


export default awsmobile;
